workflows:
  android_debug_only:
    name: Android Debug Build (with API)
    max_build_duration: 60
    environment:
      flutter: stable
      vars:
        API_BASE_URL: "https://mesibawy.com/api/"
    working_directory: mobile

    scripts:
      - name: Clean Flutter project
        script: |
          flutter clean
          flutter pub get

      - name: Ensure correct NDK version
        script: |
          echo "ndkVersion=28.1.13356709" >> android/local.properties

      - name: Build Debug APK (no release)
        script: |
          export ORG_GRADLE_JVMARGS="-Xmx4096m -Dkotlin.daemon.jvm.options=-Xmx4096m"
          flutter build apk --debug --target-platform android-arm,android-arm64,android-x64 \
            --dart-define=API_BASE_URL=${API_BASE_URL}

    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk

    cache:
      cache_paths:
        - ~/.pub-cache
        - mobile/build
        - mobile/.dart_tool
        - mobile/android/.gradle
