workflows:
  android_debug:
    name: Android Debug APK
    max_build_duration: 60
    environment:
      flutter: stable
      vars:
        # عنوان الخادم العام المستخدم داخل التطبيق أثناء البناء
        API_BASE_URL: "https://mesibawy.com/api"
    working_directory: mobile
    scripts:
      - name: Flutter pub get
        script: |
          flutter --version
          flutter pub get
      - name: Build debug APK with API_BASE_URL
        script: |
          flutter build apk --debug \
            --dart-define=API_BASE_URL=${API_BASE_URL}
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
    cache:
      cache_paths:
        - ~/.pub-cache
        - mobile/build
        - mobile/.dart_tool
        - mobile/android/.gradle

  android_release_unsigned:
    name: Android Release APK (unsigned)
    max_build_duration: 60
    environment:
      flutter: stable
      vars:
        # يمكن تغييره من واجهة Codemagic عند الحاجة لبيئات مختلفة
        API_BASE_URL: "https://mesibawy.com/api"
    working_directory: mobile
    scripts:
      - name: Flutter pub get
        script: |
          flutter --version
          flutter pub get
      - name: Build release APK (unsigned) with API_BASE_URL
        script: |
          flutter build apk --release \
            --dart-define=API_BASE_URL=${API_BASE_URL}
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    cache:
      cache_paths:
        - ~/.pub-cache
        - mobile/build
        - mobile/.dart_tool
        - mobile/android/.gradle

  android_aab_unsigned:
    name: Android Release AAB (unsigned)
    max_build_duration: 60
    environment:
      flutter: stable
      vars:
        API_BASE_URL: "https://mesibawy.com/api"
    working_directory: mobile
    scripts:
      - name: Flutter pub get
        script: |
          flutter --version
          flutter pub get
      - name: Build release AAB (unsigned) with API_BASE_URL
        script: |
          flutter build appbundle --release \
            --dart-define=API_BASE_URL=${API_BASE_URL}
    artifacts:
      - build/app/outputs/bundle/release/*.aab
    cache:
      cache_paths:
        - ~/.pub-cache
        - mobile/build
        - mobile/.dart_tool
        - mobile/android/.gradle
