workflows:
  android_debug:
    name: Android Debug APK
    max_build_duration: 120
    environment:
      flutter: stable
      vars:
        API_BASE_URL: "https://mesibawy.com/api"
    working_directory: mobile
    scripts:
      - name: Clean Flutter project
        script: |
          flutter clean
          flutter pub get
      - name: Ensure correct NDK version
        script: |
          echo "ndkVersion=28.1.13356709" >> android/local.properties
      - name: Build debug APK with API_BASE_URL
        script: |
          export ORG_GRADLE_JVMARGS="-Xmx4096m -Dkotlin.daemon.jvm.options=-Xmx4096m"
          flutter build apk --debug --target-platform android-arm,android-arm64,android-x64 \
            --dart-define=API_BASE_URL=${API_BASE_URL}
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
    cache:
      cache_paths:
        - ~/.pub-cache
        - mobile/build
        - mobile/.dart_tool
        - mobile/android/.gradle

  android_release_unsigned:
    name: Android Release APK (unsigned)
    max_build_duration: 120
    environment:
      flutter: stable
      vars:
        API_BASE_URL: "https://mesibawy.com/api"
    working_directory: mobile
    scripts:
      - name: Clean Flutter project
        script: |
          flutter clean
          flutter pub get
      - name: Ensure correct NDK version
        script: |
          echo "ndkVersion=28.1.13356709" >> android/local.properties
      - name: Build release APK (unsigned) with API_BASE_URL
        script: |
          export ORG_GRADLE_JVMARGS="-Xmx4096m -Dkotlin.daemon.jvm.options=-Xmx4096m"
          flutter build apk --release --target-platform android-arm,android-arm64,android-x64 \
            --dart-define=API_BASE_URL=${API_BASE_URL}
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    cache:
      cache_paths:
        - ~/.pub-cache
        - mobile/build
        - mobile/.dart_tool
        - mobile/android/.gradle

  android_aab_unsigned:
    name: Android Release AAB (unsigned)
    max_build_duration: 120
    environment:
      flutter: stable
      vars:
        API_BASE_URL: "https://mesibawy.com/api"
    working_directory: mobile
    scripts:
      - name: Clean Flutter project
        script: |
          flutter clean
          flutter pub get
      - name: Ensure correct NDK version
        script: |
          echo "ndkVersion=28.1.13356709" >> android/local.properties
      - name: Build release AAB (unsigned) with API_BASE_URL
        script: |
          export ORG_GRADLE_JVMARGS="-Xmx4096m -Dkotlin.daemon.jvm.options=-Xmx4096m"
          flutter build appbundle --release --target-platform android-arm,android-arm64,android-x64 \
            --dart-define=API_BASE_URL=${API_BASE_URL}
    artifacts:
      - build/app/outputs/bundle/release/*.aab
    cache:
      cache_paths:
        - ~/.pub-cache
        - mobile/build
        - mobile/.dart_tool
        - mobile/android/.gradle

  web_release:
    name: Flutter Web Build
    max_build_duration: 60
    environment:
      flutter: stable
      vars:
        API_BASE_URL: "https://mesibawy.com/api"
    working_directory: mobile
    scripts:
      - name: Clean Flutter project
        script: |
          flutter clean
          flutter pub get
      - name: Build Flutter Web
        script: |
          flutter build web --release --dart-define=API_BASE_URL=${API_BASE_URL}
    artifacts:
      - build/web/**
    cache:
      cache_paths:
        - ~/.pub-cache
        - mobile/build
        - mobile/.dart_tool
